version: "1.0"
services:
  db:
    container_name: "db"
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_lk
    ports:
      - "5432:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge